language: ruby
rvm:
- 2.4.0
script: "cd old && ./_script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - jq
sudo: false
cache: bundler
notifications:
  email:
  - colin.dean@metamesh.org
  - adam.longwill@metamesh.org
  irc:
    channels:
    - irc.freenode.net#pittmesh
    on_success: change
    on_failure: change
    # deploy:
    #   provider: heroku
    #   app: pittmesh-net
    #   api_key:
    #     secure: N5EE2AXgflG/0AvkX/DdBpZrapV57lfiTqtgwGHKip722nhvytoRzHjNr1+qKs/03A1YJnxmA6RcS7C5tCmgdLzTCfYBa3SdXaq/qUV7fimQxG6VC3Xum04Oc8T7+hY7lRGyg6oCNKVZ35G2Wk9i9vu/sqO4ePSmJFiG3vnOHKk=

