language: generic
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - jq
    - pv
before_install:
- openssl aes-256-cbc -K $encrypted_8de9452a1cf9_key -iv $encrypted_8de9452a1cf9_iv
  -in etc/deploy/ssh/id_ed25519.pittmesh.net.travis.enc -out $SSH_IDENTITY_FILE -d
  && chmod 600 $SSH_IDENTITY_FILE
install:
- cat etc/deploy/ssh/known_hosts >> $HOME/.ssh/known_hosts
- gem install html-proofer
- sudo apt-add-repository ppa:duggan/jo --yes && sudo apt-get update -q --yes && sudo
  apt-get install jo --yes
- 'scripts/notify.sh "${TRAVIS_REPO_SLUG} ${TRAVIS_BUILD_NUMBER}: [${TRAVIS_COMMIT_MESSAGE}]: ${TRAVIS_EVENT_TYPE} build underway"'
script:
- scripts/cibuild
- 'scripts/notify.sh "${TRAVIS_REPO_SLUG} ${TRAVIS_BUILD_NUMBER}: $( if [[ ${TRAVIS_TEST_RESULT} -eq 1 ]]; then echo ":x:"; else echo ":white_check_mark:"; fi )"'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SSH_IDENTITY_FILE=$HOME/.ssh/id_ed25519.pittmesh.net.travis
  - secure: ad+ToHBvOm2VhsolVsANbHh0Rk+VHjuC4Ypotr2j20PoPW3NPjNOnt9rdtQXIHpurYG6XQ2dmq1BJPiBHLJjC9GSa7hs7umI53QD7bwsQcl4TMU6BqCYMDvA+KTBD9seagEBarZthKfPwClpGesKr4mBG0eeKmMPCwoDgtfXy/Y=
  - secure: JlW2daM0lUpyaiN9fUxoN3nxRaqdZMZ8qZ4bjTbCdg5e0a8JloUKJprNTsl06f1l5/j/YA4PqQEdaV0S6efHobWSSsgywjB2X6RIUjRfL4cPFoenSl7HW1Xot4gooHtRNwBuMFbfwVoFhhxoKVebMDTqOHPSLHHd6CSvyLWfjH8=
  - secure: Nj9r8Uhr3byz7qn+Uz/t1oDjbuVdS8KBv0hKTqkIL8+W4rQLP+BCgXaPOlHNF1UfU2RFB+6CTJkbJ8eVafo93QQcZoyMO3NjwYBvNMaMDCrwiTNy0IwaEhSl/OvQerlWFD55nMBIGhzaGcFAA/RVA2ODlDMMlkQ+39a9nFUCVhk=
  - secure: fZrAUFAT8hF9sN81DEy2hvWW+qegRauvJohqWypQEbeC0xB9owgGUBg48UyI60ka3oXgfIptsY6t6PqnU76gVXbSnd2ywBDuv/1cJer7CR2Vy5BvgUBG3ctxvoAwxdwYhB30HvJsAc6eC4CEcI8172ucVFPPfppNUInuaRc09ak=
  - secure: QQ2UV/Em/glHq9TcBr0Hr8VSPLGgI+f8NlvGzaJksK96o3RPt1zczGPADZNrKbmbTSSzHjwi882NoxqjHWRDNTUX+WcMwuMnR5Bq1AhLwXyliWp+/v7TdnDGlOUadmfnZMu4XbSWq+KHuTHj4EayFOJBYRKgjDEPu3hjAT0f8mo=
deploy:
- provider: script
  skip_cleanup: true
  script: 'scripts/deploy.sh && scripts/notify.sh "${TRAVIS_REPO_SLUG} deployed, check https://pittmesh.net!"'
  on:
    branch:
    - master
    - leafletjs
