language: generic
install:
- "gem install html-proofer"
- "apt-add-repository ppa:duggan/jo --yes && apt-get update -q --yes && apt-get install jo --yes"
script:
- "scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - jq
sudo: true

