#!/usr/bin/env bash
set -e # halt script on error

# ensure that the site builds
bundle exec jekyll build

# check external links
bundle exec htmlproof ./_site

# check format of nodes manifest - necessitates
sed -e '2,$!d' -e '$d' ./node-data/nodes.json | jq . > /dev/null

# check format of links manifest - necessitates
sed -e '2,$!d' -e '$d' ./node-data/links.json | jq . > /dev/null
